### ISSUE TITLE
Vehicle keep on moving after quit

### ISSUE THREAD

**Issue by vorty123** [altmp/altv#515] opened 2020-04-16 19:04 UTC
https://www.youtube.com/watch?v=FdzlGChJ_U0

**Expected behavior**
The vehicle should stop after the player disappears

**Current behavior**
The vehicle keep on moving

**Steps to reproduce**
Start driving a car, and quit after acceleration

**Comment by FabianTerhorst** [comment] 2020-04-16 19:09
Duplicate of #362

**Closed by FabianTerhorst** 2020-04-16 19:09 UTC
Labels: Class: bug
