### ISSUE TITLE
Player ID doesn't reset on disconnect

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#438] opened 2020-02-13 10:49 UTC
**Expected behavior**
Reset ID when player disconnects

**Current behavior**
Player ID doesn't reset on disconnect

**Steps to reproduce**
F8 -> reconnect

**Detailed description**
#1007 - Beta
> [11:46:27] alt:V Multiplayer started
> [11:46:27] Started in 64775 ms
> [11:46:30] Fetching resources
> [11:46:30] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:30] Connected with id: 0
> [11:46:34] Fetching resources
> [11:46:34] Disconnected
> [11:46:34] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:34] Connected with id: 1
> [11:46:36] Fetching resources
> [11:46:36] Disconnected
> [11:46:36] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:36] Connected with id: 2
> [11:46:37] Fetching resources
> [11:46:37] Disconnected
> [11:46:37] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:37] Connected with id: 3
> [11:46:37] Fetching resources
> [11:46:37] Disconnected
> [11:46:37] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:37] Connected with id: 4
> [11:46:38] Fetching resources
> [11:46:38] Disconnected
> [11:46:38] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:38] Connected with id: 5
> [11:46:38] Fetching resources
> [11:46:38] Disconnected
> [11:46:38] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:38] Connected with id: 6
> [11:46:40] Fetching resources
> [11:46:40] Disconnected
> [11:46:40] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:40] Connected with id: 7
> [11:46:41] Fetching resources
> [11:46:41] Disconnected
> [11:46:41] Connecting to: [::ffff:127.0.0.1]:7788
> [11:46:41] Connected with id: 8

**Comment by ThomasMarangoni** [comment] 2020-02-13 10:55
alt:V is only reusing scriptIds if they are needed. Why should they reset on disconnect?

**Comment by Hardy535** [comment] 2020-02-13 11:01
Duplicate of: https://github.com/altmp/altv/issues/159
This is not a bug but intended behaviour.

**Closed** 2020-02-13 11:21 UTC
Labels: Class: bug
