### ISSUE TITLE
DevTool-Inspector crash

### ISSUE THREAD

**Issue by eiksch** [altmp/altv#490] opened 2020-03-25 18:18 UTC
Hi.

when accessing localhost:9222 to debug WebView DOM, the inspector crashes.

**Expected behavior**
Inspector should open and UI should be debuggable in Google Chrome.

**Current behavior**
Blank screen, inspector crashes with following errors in web console:
```
shell.js:3123 Uncaught TypeError: document.registerElement is not a function
    at Object.UI.registerCustomElement (shell.js:3123)
    at shell.js:3135
    at shell.js:3137
UI.registerCustomElement @ shell.js:3123
(anonymous) @ shell.js:3135
(anonymous) @ shell.js:3137
19:10:06.816 devtools_app.js:2 Uncaught ReferenceError: SDK is not defined
    at devtools_app.js:2
(anonymous) @ devtools_app.js:2
19:10:06.818 inspector.js:2 Uncaught ReferenceError: SDK is not defined
    at inspector.js:2
(anonymous) @ inspector.js:2
```

**Possible solution**
-

**Steps to reproduce**
-enable debug mode on clientside
-start server
-start game
-join server
-open/enable WebView (depending on your code)
-try to access localhost:9222
-click on the WebView you want to debug

**Context (environment)**
Chrome 80.0.3987.149 64bit
JS
React 16.13.1
RC branch #1083+

**Detailed description**
-

**Possible implementation**
-

**Comment by Lhoerion** [comment] 2020-03-25 18:20
Duplicate of #424

**Closed by Lhoerion** 2020-03-25 18:20 UTC
Labels: Class: bug, Scope: cef, Side: client, Status: duplicate

**Comment by Lhoerion** [comment] 2020-03-25 18:21
You should downgrade Chrome version to make it work apparently
