### ISSUE TITLE
Add cursor property

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#331] opened 2019-11-26 17:16 UTC
Hello,
ShowCursor () is actually a function without getter. In my opinion a variable **get/set** would be easier.

`alt.cursor = false/true`

I think it would be really easier to manage than present function.
Keep Up Great Job.
See ya

**Comment by lameule123** [comment] 2020-01-20 12:16
up

**Comment by FabianTerhorst** [comment] 2020-02-14 01:46
Duplicate of #443

**Closed by FabianTerhorst** 2020-02-14 01:46 UTC
Labels: Class: enhancement, Scope: module-api, Side: client
