### ISSUE TITLE
add event playerWeaponChange

### ISSUE THREAD

**Issue by tastydev** [altmp/altv#418] opened 2020-02-05 17:45 UTC
**Is your feature request related to a problem? Please describe.**
To easily achieve AntiCheat or Attachment mechanisms it would be nice to have a serverside "playerWeaponChange" event

**Describe the solution you'd like**
`alt.on("playerWeaponChange", (player: alt.Player, oldWeapon: number, newWeapon: number) => {
 // Do what you want.
});`

**Describe alternatives you've considered**
Build your own EventListener

**Additional context**
-none

**Comment by FabianTerhorst** [comment] 2020-02-05 17:46
Duplicate of #9

**Closed** 2020-02-06 13:28 UTC
Labels: enhancement
