### ISSUE TITLE
[Bug] vehicle.pos

### ISSUE THREAD

**Issue by Lekenthun** [altmp/altv#190] opened 2019-07-11 22:41 UTC
When the vehicle is far away (out of stream distance range) and you want to change its position then the vehicle doesn't teleport there.

**Comment by FabianTerhorst** [comment] 2019-07-11 23:03
So changing position without a near player doesn't work? Maybe thats the same reason why numberplate sometimes doesn't work.

**Comment by Lekenthun** [comment] 2019-07-11 23:04
> So changing position without a near player doesn't work? Maybe thats the same reason why numberplate sometimes doesn't work.

Yes, possible.

**Comment by vadzz-dev** [comment] 2019-07-13 23:30
Duplicate of #71

**Closed by vadzz-dev** 2019-07-13 23:30 UTC
Labels: bug
