### ISSUE TITLE
Sync Ped Decorations

### ISSUE THREAD

**Issue by Erk71** [altmp/altv#38] opened 2019-03-26 16:18 UTC
EDIT NEW:
game.setPedDecoration works for own Client. It is synced for other players AFTER the ped/player is respawned once.

EDIT OLD:
**Is your feature request related to a problem? Please describe.**
The game.setPedDecorations Decorations are not synced. Means e.g Tattoos are not synced. I have to set every tattoo of a player for every player logging in AND set the new players tattoos for every player on the server. 

**Describe the solution you'd like**
Sync similar to Face Features or Clothes.

**Describe alternatives you've considered**
It is possible to Sync on logging serverside but it is for e.g 300 players and 8 tattoos each not very efficient.

**Comment by FabianTerhorst** [comment] 2019-03-26 17:41
duplicate of #19

**Comment by Erk71** [comment] 2019-03-26 19:22
Not a duplicate. game.setPedDecoration is a different (not mentioned in #19) native which is, other than setPedHeadOverlay, setPedHeadBlend etc. not synced.

**Comment by FabianTerhorst** [comment] 2019-03-26 19:37
BTW as a workaround you don't have to call it to all players. I think it will be synced automatically.

**Comment by KifKick** [comment] 2019-03-26 19:38
Hmmm. I forgot about ped decorations.

You're right FabianTerhorst but I think it will be nice to have that too on serverside.

**Comment by FabianTerhorst** [comment] 2019-03-26 19:39
Yes ofc it would be nice to have all functions on server^^.

**Comment by KifKick** [comment] 2019-03-26 19:41
So I can add this to the list of player functions.

**Comment by KifKick** [comment] 2019-03-26 19:45
It will be easier for devs to have that in a one issue.

**Comment by Erk71** [comment] 2019-03-26 19:46
Lol. Have to Change this to Bug, IT IS SYNCED, just after the ped is respawned once.

**Comment by vadzz-dev** [comment] 2019-08-10 02:46
Should be fixed in beta branch

**Comment by vadzz-dev** [comment] 2019-08-10 02:46
Should be fixed in beta branch

**Closed** 2019-08-10 18:51 UTC
Labels: bug
