### ISSUE TITLE
[Bug] Motorcycle Engine Control

### ISSUE THREAD

**Issue by lsvMoretti** [altmp/altv#363] opened 2019-12-29 09:36 UTC
When using manual engine control for a motorcycle, you are able to press W / Accelerator to start 

## Expected Behavior

Our system uses manual engine control for all vehicles. All the classes I have tested so far seem to work as expected, this should obviously be expected for motorcycles as well. When trying to turn off, the vehicle should remain off
## Current Behavior

Motorcycle manual engine control doesn't seem to work correctly. You are able to force the engine on and unable to turn it off with /engine.
## Possible Solution

Could need the play flag setting on vehicle enter?
## Steps to Reproduce

1. Spawn motorcycle
2. Set manual engine control to true
3. Enter motorcycle and engine starts
## Context (Environment)

It's not too major, just using a fuel system it can drain the fuel with the engine being always on.

**Comment by WhishN** [comment] 2019-12-29 09:48
did u use 
`native.setPedConfigFlag(alt.Player.local.scriptID, 429, true); // Disable engine Turn on`
otherwise it is possible to turn on vehicles aswell

**Comment by lsvMoretti** [comment] 2019-12-29 13:04
No, I am using C# server side and they have a manual engine control function, this works for all vehicles expect motorcycle

**Comment by WhishN** [comment] 2019-12-29 21:01
https://github.com/altmp/altv/issues/184#issue-464896719

**Comment by Lhoerion** [comment] 2020-02-06 17:18
Duplicate of #184

**Closed by Lhoerion** 2020-02-06 17:18 UTC
Labels: bug, duplicate, server
