### ISSUE TITLE
Blood is not synced on death

### ISSUE THREAD

**Issue by vorty123** [altmp/altv#425] opened 2020-02-06 20:34 UTC
## Expected Behavior
When a player dies, the blood from his/her skin is removed.

## Current Behavior
Now its only removed client-side, for the player, the other players see him/her bloody.

## Possible Solution
Reset blood level on death.

**Comment by tastydev** [comment] 2020-02-11 04:56
Duplicate of #219

**Closed** 2020-02-11 10:27 UTC
Labels: Class: bug, Scope: natives, Side: client, Status: duplicate
