### ISSUE TITLE
Server Event 'serverReady'

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv#474] opened 2020-03-11 08:47 UTC
**Is your feature request related to a problem? Please describe.**
Need to know for server startup routine if the server is started and all resources are loaded.

**Describe the solution you'd like**
`alt.on('serverReady')`

**Additional context**
I've using some more resources and in different resources i need to know, when the server is fully loaded and ready. For Examples: To spawn vehicles on server startup, i have to load the resource with modded vehicles at first to be sure that the vehicles are loaded. if not, server comes with error, that the vehicle hash is not correct.

**Comment by vadzz-dev** [comment] 2020-03-11 09:32
In your case you should just use deps

**Comment by Revyn112** [comment] 2020-03-11 09:35
Forgot to mention that im using c# serverside.

**Comment by Lhoerion** [comment] 2020-03-11 09:42
Duplicate of #33

**Closed by Lhoerion** 2020-03-11 09:42 UTC
Labels: Class: enhancement, Scope: module-api, Side: server, Status: duplicate
