### ISSUE TITLE
start, stop, restart server functions

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv#255] opened 2019-09-07 00:41 UTC
First of all, I'm truly glad that we are able to controll resources.
I think it would be even better if we could do this with server side functions.

For example:
alt.restartResource("resourcename");
alt.startResource("resourcename");
alt.stopResource("resourcename");
alt.isRunningResource("resource-name")
alt.getResources() // return all resource name

**Comment by vadzz-dev** [comment] 2019-09-07 00:47
Thought about it too, most likely will be implemented in near future

**Comment by FabianTerhorst** [comment] 2019-09-07 08:15
Duplicate of #21

**Comment by Lekenthu** [comment] 2019-09-07 23:02
New ideas:
alt.isRunningResource("resource-name")
alt.getResources() // return all resource name

**Comment by vadzz-dev** [comment] 2019-09-09 22:18
Move future discussion to #21

**Closed by vadzz-dev** 2019-09-09 22:18 UTC
Labels: enhancement
