### ISSUE TITLE
IPlayer.Ammo returns 0

### ISSUE THREAD

**Issue by lsvMoretti** [altmp/altv#328] opened 2019-11-21 15:31 UTC
Using AltV.Net, the IPlayer.Ammo returns 0, with 100 ammo in the current weapon.

https://i.imgur.com/glhx9Ou.jpg

`player.SendInfoMessage($"Ammo: {player.Ammo}, Ammo Int: {Convert.ToInt32(player.Ammo)}");`

**Comment by Lhoerion** [comment] 2020-02-12 00:32
Does it happen on latest build #1004?
Is it C# module issue or JS module too?

**Comment by lsvMoretti** [comment] 2020-02-20 20:29
Hey sorry, I've been not too well last few days.

I've just tested with the latest release branch in C# (I don't use JS server side to test) and the latest AltV.Net packages and it returns 0 when I have 10 in the gun.

**Comment by FabianTerhorst** [comment] 2020-02-23 18:25
I think that getter isn't implemented thats probably why node module doesn't have it.

**Comment by FabianTerhorst** [comment] 2020-02-23 18:26
Also kinda duplicate of #309

**Closed by FabianTerhorst** 2020-02-23 18:26 UTC
Labels: Class: enhancement, Priority: medium, Side: server
