### ISSUE TITLE
isVisible WebView Property not working

### ISSUE THREAD

**Issue by lameule123** [altmp/altv#466] opened 2020-03-07 23:08 UTC
**Expected behavior**
Set display of webview to off when set to false.

**Current behavior**
Nothing

**Possible solution**
Alot but this one is the most simple in alot of case.

**Steps to reproduce**
- Create a webview
- Set isVisible to false
- No change

**Comment by Lhoerion** [comment] 2020-03-07 23:09
Duplicate of #335

**Closed by Lhoerion** 2020-03-07 23:09 UTC
Labels: Class: bug, Scope: module-api, Side: client, Status: duplicate

**Comment by SandDanGlokta** [comment] 2020-04-13 12:59
needs a fix urgently
