### ISSUE TITLE
Vehicle door sync not for all players

### ISSUE THREAD

**Issue by Kingwolfi** [altmp/altv#482] opened 2020-03-16 16:53 UTC
If the Server opens a vehicle door not every player gets the animation sync

**Expected behavior**
Every player in range should see the door open/close

**Current behavior**
only the LAST player connected to the server sees the animation (in case of two players) 

**Steps to reproduce**
- login 2 players (A and B) in streaming range to the vehicle
- activate a server command to open/close a vehicle door (player A or B)
- PlayerA: door animation
- PlayerB: NO animation
- Reconnect PlayerB
- activate a server command to open/close a vehicle door (player A or B)
- PlayerA: NO animation
- PlayerB: door animation
- Reconnect PlayerA
- activate a server command to open/close a vehicle door (player A or B)
- PlayerA: door animation
- PlayerB: NO animation

Server side c# code:
vehicle.SetDoorStateAsync((byte)DoorID.DoorTrunk, (byte)DoorState.DoorOpened);
or
vehicle.SetDoorState((byte)DoorID.DoorTrunk, (byte)DoorState.DoorOpened);

**Comment by FabianTerhorst** [comment] 2020-03-16 16:54
Duplicate of #169

**Closed by FabianTerhorst** 2020-03-16 16:54 UTC
Labels: Class: bug
