### ISSUE TITLE
alt.WebView.isVisible is opposite

### ISSUE THREAD

**Issue by dexslab** [altmp/altv#495] opened 2020-04-01 03:34 UTC
alt.WebView.isVisible is backwards
When using isVisible when true the webveiw should be seen but it is not. When it returns false the webview is visible.

**Expected behavior**
isVisible should be true when the particular webview is visible.

**Current behavior**
When webview isvisble then webview.isvisible is false.

**Possible solution**
Alter the code to show the opposite

**Steps to reproduce**
Create a webview
check isvisible
show webview 
check isvisible

**Context (environment)**
Just making me change my signs

**Comment by Lhoerion** [comment] 2020-04-01 12:42
Duplicate of #335

**Closed by Lhoerion** 2020-04-01 12:42 UTC
Labels: Class: bug, Scope: module-api, Side: client, Status: duplicate, Status: question
