### ISSUE TITLE
DLC doesn't unload if resource stops

### ISSUE THREAD

**Issue by Xenius97** [altmp/altv#439] opened 2020-02-13 11:02 UTC
**Expected behavior**
Unload DLC when resource stops

**Current behavior**
DLC doesn't unload if resource stops
If I change something in DLC resource, and I restart the script I can't see the changes, just when I restart the game.

**Steps to reproduce**
Load a dlc resource and stop it.

**Comment by vadzz-dev** [comment] 2020-02-13 11:22
duplicate of #193

**Closed by vadzz-dev** 2020-02-13 11:22 UTC
Labels: Class: bug
