### ISSUE TITLE
Vue.js mouse events handling from child elements

### ISSUE THREAD

**Issue by wenddak1ng** [altmp/altv#333] opened 2019-11-28 13:06 UTC
## Expected Behavior

In actually chrome build if I'm set @click or another mouse event to component, all child elements always handling this event
## Current Behavior

In 72 build (alt:V cef) has a trouble with handling events. If you clicking on elements which created by vue component, any mouse events may be willn't fire
## Possible Solution

Update CEF

**Comment by stpnov** [comment] 2019-11-28 13:51
https://vuejs.org/v2/guide/events.html
`<div v-on:click.self="doThat">...</div>`

**Comment by wenddak1ng** [comment] 2019-12-04 18:19
> https://vuejs.org/v2/guide/events.html
> `<div v-on:click.self="doThat">...</div>`

It's not as easy as it looks. All vue modifiers like `.native`/`.self`/`.prevent` etc doesn't fix this issue. I tried to add a user click listener and all clicks worked. This issue currently in this CEF version or by multiplayer authors' mistake

**Comment by stpnov** [comment] 2020-01-07 17:01
Really a problem exists

**Comment by Lhoerion** [comment] 2020-02-12 00:20
Duplicate of #430

**Closed by Lhoerion** 2020-02-12 00:20 UTC
Labels: Class: bug, Scope: cef, Side: client, Status: duplicate
